version: "3"
services:
  vulnerable-services:
    image: brannondorsey/app-sec-workshop:vulnerable-services
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        FILES_TO_REMOVE: attacker-controlled-services
    container_name: vulnerable-services
    hostname: vulnerable-services
    restart: unless-stopped
    environment:
      DEBUG: '1'
    ports:
      - 8080:8080
    entrypoint: ['npm', 'run', 'start-vulnerable']
  attacker-controlled-services:
    image: brannondorsey/app-sec-workshop:attacker-controlled-services
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        FILES_TO_REMOVE: vulnerable-services
    container_name: attacker-controlled-services
    hostname: attacker-controlled-services
    restart: unless-stopped
    ports:
      - 1337:1337
    entrypoint: ['npm', 'run', 'start-attacker-controlled']
